# Generated by Django 6.0.5 on 2026-06-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("ptype", models.SmallIntegerField(db_index=True, default=1)),
                ("genre", models.SmallIntegerField(db_index=True, default=1)),
                ("status", models.SmallIntegerField(db_index=True, default=1)),
                ("click_num", models.IntegerField(default=0)),
                ("word_num", models.IntegerField(default=0)),
                ("praise_num", models.IntegerField(default=0)),
                ("like_num", models.IntegerField(default=0)),
                ("has_banner", models.BooleanField(db_index=True, default=False)),
                ("review_num", models.IntegerField(default=0)),
                ("comment_num", models.IntegerField(default=0)),
                ("cover", models.URLField(blank=True, max_length=500, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                ("db_update", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novels",
                        to="novels.author",
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novels",
                        to="novels.contest",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="novels", to="novels.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-last_update"],
            },
        ),
    ]
