# Generated by Django 6.0.5 on 2026-06-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novel",
            name="click_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="novel",
            name="comment_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="novel",
            name="like_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="novel",
            name="praise_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="novel",
            name="review_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="novel",
            name="word_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
