# Generated by Django 6.0.5 on 2026-06-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0002_alter_novel_click_num_alter_novel_comment_num_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "novel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task",
                        to="novels.novel",
                    ),
                ),
            ],
            options={
                "ordering": ["-novel__last_update"],
            },
        ),
    ]
