# Generated by Django 6.0.5 on 2026-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0003_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="contest",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="novel",
            name="cover",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
