# Generated by Django 6.0.5 on 2026-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0004_alter_author_options_alter_contest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("u", "urgent"), ("d", "default"), ("f", "finished")],
                default="d",
                max_length=1,
            ),
        ),
    ]
