# Generated by Django 6.0.5 on 2026-06-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0005_task_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["genre", "status"], name="novels_nove_genre_bfd3b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["has_banner", "-last_update"],
                name="novels_nove_has_ban_3f8b9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["-click_num"], name="novels_nove_click_n_70e8cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["author"], name="novels_nove_author__06ece1_idx"
            ),
        ),
    ]
