# Generated by Django 6.0.5 on 2026-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0006_add_composite_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="novel",
            name="genre",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="novel",
            name="has_banner",
            field=models.BooleanField(default=False),
        ),
    ]
