# Generated by Django 6.0.5 on 2026-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0007_remove_redundant_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="novel",
            index=models.Index(
                fields=["contest"], name="novels_nove_contest_e34447_idx"
            ),
        ),
    ]
