# Generated by Django 6.0.5 on 2026-06-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0008_add_contest_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="novel",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("last_update"), descending=True, nulls_last=True
                    )
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    models.Case(
                        models.When(status="l", then=0),
                        models.When(status="u", then=1),
                        models.When(status="d", then=2),
                        models.When(status="f", then=3),
                        default=4,
                    ),
                    "-novel_id",
                ]
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("l", "long_term"),
                    ("u", "urgent"),
                    ("d", "default"),
                    ("f", "finished"),
                ],
                default="d",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="NovelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("click_num", models.IntegerField(null=True)),
                ("like_num", models.IntegerField(null=True)),
                ("praise_num", models.IntegerField(null=True)),
                ("word_num", models.IntegerField(null=True)),
                ("review_num", models.IntegerField(null=True)),
                ("comment_num", models.IntegerField(null=True)),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="novels.novel",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["snapshot_date"], name="novels_nove_snapsho_8cd574_idx"
                    ),
                    models.Index(
                        fields=["novel", "snapshot_date"],
                        name="novels_nove_novel_i_10dc9d_idx",
                    ),
                ],
                "unique_together": {("novel", "snapshot_date")},
            },
        ),
    ]
