# Generated by Django 6.0.5 on 2026-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "author",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "contest",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("ptype", models.IntegerField(blank=True, null=True)),
                ("genre", models.IntegerField(blank=True, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("click_num", models.IntegerField(blank=True, null=True)),
                ("word_num", models.IntegerField(blank=True, null=True)),
                ("praise_num", models.IntegerField(blank=True, null=True)),
                ("like_num", models.IntegerField(blank=True, null=True)),
                ("has_banner", models.BooleanField()),
                ("review_num", models.IntegerField(blank=True, null=True)),
                ("comment_num", models.IntegerField(blank=True, null=True)),
                ("last_update", models.DateTimeField(blank=True, null=True)),
                ("db_update", models.DateTimeField(auto_now=True)),
                ("cover", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "novel",
                "ordering": [
                    "-id",
                    "-last_update",
                    "-click_num",
                    "-praise_num",
                    "-like_num",
                    "-word_num",
                    "has_banner",
                    "-review_num",
                    "-comment_num",
                    "title",
                    "ptype",
                    "genre",
                    "status",
                    "author",
                    "contest",
                    "db_update",
                    "cover",
                ],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Noveltaglink",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tag_id",
                        "novel_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "noveltaglink",
                "ordering": ["-novel_id", "-tag_id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "tag",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
    ]
