name: auto2

on:
  schedule:
    - cron: "44 06 * * *"
  workflow_dispatch:
    inputs:
      num:
        required: false
        default: ""

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Auto read BEGIN
        run: |
          if [ -f BEGIN.txt ]; then
            echo "BEGIN=$(cat BEGIN.txt)" >> "$GITHUB_ENV"
          else
            echo "BEGIN=1" >> "$GITHUB_ENV"
          fi

      - name: Set NUM
        run: |
          if [ -n "${{ inputs.num }}" ]; then
            echo "NUM=${{ inputs.num }}" >> "$GITHUB_ENV"
          else
            echo "NUM=200" >> "$GITHUB_ENV"
          fi

      - name: Run spider
        run: |
          set -o pipefail
          mkdir -p output
          uv run scrapy crawl meta_spider -a begin=${{ env.BEGIN }} -a num=${{ env.NUM }} -o output/meta.jsonl

      - name: Update BEGIN
        run: |
          NEW_BEGIN=$(( ${{ env.BEGIN }} + ${{ env.NUM }} - 5 ))
          if (( NEW_BEGIN < 1 )); then
            NEW_BEGIN=1
          fi
          echo $NEW_BEGIN > BEGIN.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add output/meta.jsonl
          git add -f BEGIN.txt
          git commit -m "Auto update" --allow-empty
          git push origin main