name: sfacg-metadata-crawler-beta

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  crawl:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Run spider
        run: uv run scrapy crawl meta_spider -o meta.jsonl 2>&1 | tee crawler_log.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update"
          git push -f origin HEAD:workflows
