name: sfacg-metadata-crawler-beta

on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      begin:
        description: "Start page number"
        required: false
        default: ""
      num:
        description: "Number"
        required: false
        default: ""

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Echo variables at start
        run: |
          echo "inputs.begin: ${{ inputs.begin }}"
          echo "inputs.num: ${{ inputs.num }}"
          echo "vars.BEGIN: ${{ vars.BEGIN }}"
          echo "vars.NUM: ${{ vars.NUM }}"

      - name: Run spider
        run: |
          set -o pipefail
          mkdir -p output
          uv run scrapy crawl meta_spider -a begin=${{ vars.BEGIN }} -a num=1 -o output/meta.jsonl

      - name: Update BEGIN = BEGIN + 1
        if: ${{ github.event_name == 'schedule' || inputs.begin == '1' }}
        run: |
          NEW_BEGIN=$(( ${{ vars.BEGIN }} + 1 ))
          gh variable set BEGIN -b $NEW_BEGIN

      - name: Echo variables at end
        run: |
          echo "inputs.begin: ${{ inputs.begin }}"
          echo "inputs.num: ${{ inputs.num }}"
          echo "vars.BEGIN: ${{ vars.BEGIN }}"
          echo "vars.NUM: ${{ vars.NUM }}"

      - name: Commit and push to workflow branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git checkout -B data-branch
          git add output/meta.jsonl
          git commit -m "Auto update" --allow-empty
          git push -f origin data-branch